### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CiTroNaK** [devonjones/PSRD-Parser#10]
Hi,
first of all thank you very much for this parser :-)

I found these errors.

`./run_classes.sh`

```
Core Rulebook: Barbarian
Core Rulebook: Bard
Core Rulebook: Cleric
Traceback (most recent call last):
  File "./class_parse.py", line 34, in <module>
    sys.exit(main())
  File "./class_parse.py", line 31, in main
    exec_main(parser, fxn, "classes")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 34, in exec_main
    function(arg, options.output, options.book)
  File "/home/petr/PSRD-Parser/src/psrd/classes.py", line 250, in parse_core_classes
    core_class = parse_class(struct, book)
  File "/home/petr/PSRD-Parser/src/psrd/classes.py", line 211, in parse_class
    cl = stat_block_pass(cl, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/__init__.py", line 47, in stat_block_pass
    newsections.append(stat_block_pass(s, book, no_sb=no_sb))
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/__init__.py", line 45, in stat_block_pass
    newsections.append(parse_stat_block(s, book, no_sb=no_sb))
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/utils.py", line 46, in parse_stat_block
    return function(sb, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/animal_companion.py", line 34, in parse_animal_companion
    animal_companion_parse_function(key)(ac, value)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/animal_companion.py", line 28, in animal_companion_parse_function
    return functions[field.lower()]
KeyError: u'starting statistics'
```

`./run_feats.sh`

```
Ultimate Combat: Whip Mastery
Traceback (most recent call last):
  File "./feat_parse.py", line 17, in <module>
    sys.exit(main())
  File "./feat_parse.py", line 14, in main
    exec_main(parser, parse_feats, "feats")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 34, in exec_main
    function(arg, options.output, options.book)
  File "/home/petr/PSRD-Parser/src/psrd/feats.py", line 127, in parse_feats
    struct = quote_pass(struct)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 77, in quote_pass
    quote_pass(item)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 76, in quote_pass
    for item in section.get('sections', []):
AttributeError: StatBlockHeading instance has no attribute 'get'
```

`./run_rules.sh`

```
--# Description
Bestiary: Introduction
Traceback (most recent call last):
  File "./rules_parse.py", line 21, in <module>
    sys.exit(main())
  File "./rules_parse.py", line 18, in main
    exec_main(parser, fxn, "rules")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 32, in exec_main
    function(arg, options.output, options.book, options.title)
  File "/home/petr/PSRD-Parser/src/psrd/rules.py", line 202, in parse_rules
    rules = ability_pass(rules)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 59, in ability_pass
    ability_pass(s)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 59, in ability_pass
    ability_pass(s)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 56, in ability_pass
    section_filter_ability_type(section)
  File "/home/petr/PSRD-Parser/src/psrd/sections.py", line 18, in section_filter_ability_type
    if section.has_key('name'):
AttributeError: StatBlockHeading instance has no attribute 'has_key'
```

`./run_spell_lists.sh`

```
Core Rulebook: 9th-Level Sorcerer/Wizard Spells
Traceback (most recent call last):
  File "./spell_list_parse.py", line 16, in <module>
    sys.exit(main())
  File "./spell_list_parse.py", line 13, in main
    exec_main(parser, parse_spell_lists, "spell_lists")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 34, in exec_main
    function(arg, options.output, options.book)
  File "/home/petr/PSRD-Parser/src/psrd/spell_lists.py", line 136, in parse_spell_lists
    struct = parse_universal(filename, output, book)
  File "/home/petr/PSRD-Parser/src/psrd/universal.py", line 376, in parse_universal
    fp = open(filename)
IOError: [Errno 2] No such file or directory: '/home/petr/pfsrd-web/paizo.com/pathfinderRPG/prd/advancedClassGuide/spellLists.html'
```

`./run_spells.sh`

```
Advanced Class Guide: Contingent Scroll
Advanced Class Guide: Creeping Ice
Traceback (most recent call last):
  File "./spell_parse.py", line 21, in <module>
    sys.exit(main())
  File "./spell_parse.py", line 12, in main
    exec_main(parser, parse_spell, "spells")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 34, in exec_main
    function(arg, options.output, options.book)
  File "/home/petr/PSRD-Parser/src/psrd/spells.py", line 134, in parse_spell
    struct = stat_block_pass(struct, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/__init__.py", line 52, in stat_block_pass
    return parse_stat_block(section, book, no_sb=no_sb)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/utils.py", line 46, in parse_stat_block
    return function(sb, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/spell.py", line 48, in parse_spell
    spell_parse_function(key)(spell, value)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/spell.py", line 42, in spell_parse_function
    return functions[field.lower()]
KeyError: u'or area'
```

`./run_creatures.sh`

```
Bestiary: Gorgon

Bestiary: Gray Ooze
Bestiary: Green Hag

Bestiary: Griffon

Bestiary: Half-Celestial
Traceback (most recent call last):
  File "./creature_parse.py", line 17, in <module>
    sys.exit(main())
  File "./creature_parse.py", line 14, in main
    exec_main(parser, parse_creature, "creatures")
  File "/home/petr/PSRD-Parser/src/psrd/options.py", line 34, in exec_main
    function(arg, options.output, options.book)
  File "/home/petr/PSRD-Parser/src/psrd/creatures.py", line 77, in parse_creature
    struct = stat_block_pass(struct, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/__init__.py", line 45, in stat_block_pass
    newsections.append(parse_stat_block(s, book, no_sb=no_sb))
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/utils.py", line 46, in parse_stat_block
    return function(sb, book)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/creature.py", line 45, in parse_creature
    parse_creature_descriptors(creature, descriptors)
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/creature.py", line 360, in parse_creature_descriptors
    parse_creature_descriptor(creature, real.pop())
  File "/home/petr/PSRD-Parser/src/psrd/stat_block/creature.py", line 408, in parse_creature_descriptor
    raise Exception('well fuck: %s' %(values))
Exception: well fuck: [u'dragon']
```

Could you please help me?

I would like to help, but I know nothing about Python... If you write me what to do to fix it, i will try to help you.

Thank you very much.

Best regards,
Petr

**Comment by devonjones** [comment]
Hey, so the main problem you are running into is that paizo's site has some bugs that are too onerous to fix in the parser.  what I do is apply a few small patches to their site first before I run the parser.  if you want I can upload those as a .patch file (for use with the tools patch & diff).

If however, what you want is access to the final data files it produces, there's a whole repo of just the final data:

https://github.com/devonjones/PSRD-Data

As for areas of help, I've got a lot of intermediate steps that need some attention that don't require being able to do the initial parse of the html.  My main focus has been on drawing out more metadata from what I parse (for example, I now have a part of the tool that can pull out the AC of a monster, as well as all of the components of the AC like dodge, dex, etc and ensure that the calculated ac is correct).  I can point you to some of these areas of work if that sounds interesting.

**Comment by CiTroNaK** [comment]
Hi, sorry for the delay. Please send the patches. I would like to try them.

I found the repo with SQLite databases, thank you. I learned a lot from it (especially from storing this type of data in database).

Best regards,
Petr

**Comment by devonjones** [comment]
I added a file under data that contains the patch.

Their latest data drop has broken the parser in a few places so I'm chasing them down now (this happens every release since they are hand coding their site)

**Comment by devonjones** [comment]
Just uploaded a new version.  Everything except monster parsing should be fixed.  a few monsters are still busted

bestiary_3/creatures/animal_lord.json
bestiary_3/creatures/graveknight.json
bestiary_3/creatures/penanggalen.json
mythic_adventures/creatures/phoenix.json

Lemme know if you see different behavior

**Comment by CiTroNaK** [comment]
Thank you. 

I was able to use the patch file with 
```
git apply --ignore-whitespace --reject ~/Downloads/pfsrd-web.patch
```

Few changes was rejected

```
feats.html.rej
hunter.html.rej
index.html.rej
skald.html.rej
slayer.html.rej
spelllists.html.rej
updates.html.rej
warpriest.html.rej
```

I changed this files manually and replace `strong` => `b` and `em` => `i`.

I found *animal_lord* busted too, so I suppose others will be too (I don't know how to skip monster). The file with *animal_lord* has html errors (wrong `div`), but even when I fixed them It not helped.

**Comment by devonjones** [comment]
I just finished getting the latest data drop from paizo to parse.  I've pushed a new patch and a few minor changes to the python.

**Comment by CiTroNaK** [comment]
Thank you. I will try it.

**Comment by CiTroNaK** [comment]
Could you please update https://github.com/devonjones/PSRD-Data so I could compare it with my result? Thank you.

**Comment by CiTroNaK** [comment]
Hi. I switched to Ubutnu and tried it. `./run_all.sh` without any issues. But `./load_json.sh` return:

```
# Core Rulebook
/home/petr/workspace/PF-Data/core_rulebook/urlref.json
Traceback (most recent call last):
  File "./url_ref_loader.py", line 16, in <module>
    sys.exit(main())
  File "./url_ref_loader.py", line 13, in main
    exec_load_main(parser, load_url_references)
  File "/home/petr/workspace/PSRD-Parser/src/psrd/options.py", line 42, in exec_load_main
    function(options.db, args, options.parent)
  File "/home/petr/workspace/PSRD-Parser/src/psrd/url_ref.py", line 30, in load_url_references
    load_url_reference(conn, struct)
  File "/home/petr/workspace/PSRD-Parser/src/psrd/url_ref.py", line 15, in load_url_reference
    raise Exception("'%s'" % item['new'])
Exception: 'pfsrd://Core Rulebook/Classes/Paladin/Class Features/Mercy/Blinded'
```

Could it be problem with `jsonschema"? I've installed it using `sudo apt-get install python-jsonschema`. 

Thank you.

**Comment by devonjones** [comment]
So pathfinder open reference gives every piece of content a url.  I make
sure over time that no url ever breaks.  What this mean is that one of my
existing url redirects is now pointing at a url that's missing.

I can bang out the changes from this latest load and that part should work.

Devon

**Comment by devonjones** [comment]
ok, so a couple parts of the process that I didn't have publicly available are now there.

The basic process for me looks something like this

1) go to my pfsrd-web git repo, which I can't make public because it's to store paizo's website.
1.1) Checkout master.
1.2) rm -rf
1.3) wget the paizo site: wget -rp --no-parent http://paizo.com/pathfinderRPG/prd/
1.4) commit the changes
1.5) checkout the modified branch
1.6) git merge master
1.7) clean up any conflicts.
1.8) (new) create a patch file to check into PSRD-Parser

2) Go to PSRD-Parser and run the html to json conversion
2.1) under PSRD-Data, check out initial_load branch
2.1) cd src
2.2) ./run_all.sh
2.3) go back and fix any exceptions, probably by patching the stuff in web.
2.4) commit any changes
2.5) go over to PSRD-Data and commit any changes

3) Merge in manual json changes.
3.1) go to PSRD-Data and check out modified
3.2) git merge master
3.3) fix conficts
3.4) commit

4) Go back to PSRD-Parser to load json
4.1) run load_json.sh
4.2) if I get any exceptions like the one you saw, I go use sqlite3 to go look in the database for the book that broke, find the new url by querying, and add it to structure/<book name>/urlref.json
(note that one only happens if I've /already/ aliased the url in the past and it moved again).
4.3) finish the load and go commit everything in PSRD-Data *except* supportedurllist.txt and urllist.txt. I use the diff on those files to ensure that any url changes get added into urlref.json files for the appropriate books.
4.4) once those are all in, and the only changes to urllist.txt are adds, I commit everything.

Now, I had not made the initial_load and modified branches available until now, because this was all just my process for running things and no one else was doing it.  those are now in the public repo.

**Comment by devonjones** [comment]
It's worht noting that i can normally do this in a day or two, but paizo dropped a ton of eratta along with structural html changes in this last batch, so it's just been a larger pain then normal

**Comment by devonjones** [comment]
Also worht noting is that whre I can use the most help is on finding ways to minimize the delta on the modified branch for the json files by driving more intelligence into the parser, or pushing changes back to the web site.

Beyond that I want to also pull out more metadata from objects like say items/monsters/feats/etc so I can drive more intelligence into the data making it easy for people to reuse this data for smarter apps.

**Comment by CiTroNaK** [comment]
Thank you for info and your time. Did you try to ask Paizo about the data? They must have them in better format than non-valid HTML.

I am now trying to transfer data from your SQLite to Ruby on Rails app (I chosen to create a little app for PF to learn Ruby on Rails). I found a lot of minor or major problem in data (eg. slots of items https://www.dropbox.com/s/ncx4y73wn520u1z/item_slots.csv?dl=0). I can send you more info about problems that I found.

**Comment by devonjones** [comment]
So paizo doesn't keep this stuff in a computer parsable format.  So far as I know this project is the best public data set of the srd.

Yes, there's some cleanup to do on the data.  If you use the finalized data in the PSRD-Data project master branch, it's much cleaner, but problems like the slot stuff I see in there do make it through.

a huge area of value would be a set of tests against the databases to make sure we don't have those kinds of data problems.  Those could be run when I complete a load and then I can go track down the culprits.

And yeah, sure, send me more info. Anything you find is a big win for me to catch and clean, especially if I can make that into some sort of test that is permanent for future loads.

**Comment by CiTroNaK** [comment]
It's really a shame that Paizo has not data more accessible.

Yes, I use your PSRD-Data SQLite files from master branch. 

Is this format ok? https://gist.github.com/CiTroNaK/8a8bbf3867b2513f54d3
